# Generated by Django 5.2.4 on 2025-11-30 10:23

import base.validators.photos
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kitchen_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this kitchen category"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this category currently active?"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order in which to display categories"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Category description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Category image",
                        null=True,
                        upload_to="menu_categories/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this category active?"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "position",
                    models.CharField(help_text="Job title/position", max_length=100),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department (e.g., Kitchen, Service, Management)",
                        max_length=100,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly salary",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Kitchen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Kitchen name/identifier", max_length=255
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location in restaurant (e.g., Ground Floor - Left)",
                        max_length=255,
                    ),
                ),
                (
                    "max_capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum orders this kitchen can handle simultaneously",
                        null=True,
                    ),
                ),
                (
                    "kitchen_staff",
                    models.ForeignKey(
                        help_text="Employee on this kitchen",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_kitchen",
                        to="core.employee",
                    ),
                ),
                (
                    "kitchen_category",
                    models.ForeignKey(
                        help_text="To which kitchen category, this kitchen falls?",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kitchen_type",
                        to="core.kitchen_category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=255)),
                ("description", models.TextField(help_text="Product description")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Product price", max_digits=10
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Discounted price (if any)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="default_images/profile.png",
                        upload_to=base.validators.photos.upload_path_user,
                        validators=[base.validators.photos.validate_image],
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Is this Product currently available?"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Display order within category"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Product category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_category",
                        to="core.menu",
                    ),
                ),
                (
                    "kitchen",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which kitchen prepares this Product?",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_from",
                        to="core.kitchen",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        help_text="Unique order number", max_length=50, unique=True
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("dine_in", "Dine In"),
                            ("takeaway", "Takeaway"),
                            ("delivery", "Delivery"),
                        ],
                        default="dine_in",
                        max_length=20,
                    ),
                ),
                (
                    "table_number",
                    models.CharField(
                        blank=True,
                        help_text="Table number (for dine-in)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "delivery_address",
                    models.TextField(
                        blank=True, help_text="Delivery address (for delivery orders)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("served", "Served"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("card", "Card"),
                            ("online", "Online"),
                            ("wallet", "Digital Wallet"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Subtotal before tax and discount",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Tax amount",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Discount amount",
                        max_digits=10,
                    ),
                ),
                (
                    "delivery_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Delivery charge (if applicable)",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Final total amount",
                        max_digits=10,
                    ),
                ),
                (
                    "ordered_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the order was placed"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the order was confirmed", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the order was completed", null=True
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Customer who placed the order",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="customer.customer",
                    ),
                ),
                (
                    "served_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who served this order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="served_orders",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of items ordered",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit at time of order",
                        max_digits=10,
                    ),
                ),
                (
                    "dietary_type",
                    models.CharField(
                        choices=[
                            ("veg", "Vegetarian"),
                            ("non_veg", "Non-Vegetarian"),
                            ("vegan", "Vegan"),
                            ("gluten_free", "Gluten Free"),
                        ],
                        default="veg",
                        max_length=20,
                    ),
                ),
                (
                    "spice_level",
                    models.CharField(
                        choices=[
                            ("none", "No Spice"),
                            ("mild", "Mild"),
                            ("medium", "Medium"),
                            ("hot", "Hot"),
                            ("extra_hot", "Extra Hot"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "serving_size",
                    models.CharField(
                        blank=True,
                        help_text="Serving size (e.g., '1 plate', '250g')",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("served", "Served"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "prepared_at",
                    models.DateTimeField(
                        blank=True, help_text="When item preparation started", null=True
                    ),
                ),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True, help_text="When item was ready", null=True
                    ),
                ),
                (
                    "served_at",
                    models.DateTimeField(
                        blank=True, help_text="When item was served", null=True
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        help_text="Product being ordered",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="core.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="core.orders",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
