# Generated by Django 5.2.4 on 2025-12-02 11:05

import base.validators.photos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_menuitem_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="default_images/profile.png",
                upload_to="menu_item/",
                validators=[base.validators.photos.validate_image],
            ),
        ),
    ]
