# Generated by Django 5.2.4 on 2025-12-03 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_menuitem_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kitchen",
            old_name="kitchen_category",
            new_name="category",
        ),
        migrations.RemoveField(
            model_name="kitchen",
            name="kitchen_staff",
        ),
        migrations.AddField(
            model_name="employee",
            name="kitchen_assigned",
            field=models.ForeignKey(
                blank=True,
                help_text="Kitchen to which the employee is assigned",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kitchen_employees",
                to="core.kitchen",
            ),
        ),
    ]
