# Generated by Django 5.2.4 on 2025-12-03 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_kitchen_category_kitchen_category_and_more"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="unit_price",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="ordered_at",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="total_amount",
        ),
        migrations.AlterField(
            model_name="orders",
            name="customer",
            field=models.ForeignKey(
                default="",
                help_text="Customer who placed the order",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="customer.customer",
            ),
        ),
    ]
