# Generated by Django 5.2.4 on 2025-12-03 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_orderitem_unit_price_remove_orders_ordered_at_and_more"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer who placed the order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="customer.customer",
            ),
        ),
    ]
