# Generated by Django 5.2.4 on 2025-07-26 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                ("district_id", models.PositiveIntegerField(unique=True)),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Name"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                ("province_id", models.PositiveIntegerField(unique=True)),
                (
                    "name",
                    models.CharField(max_length=70, unique=True, verbose_name="Name"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
            },
        ),
        migrations.CreateModel(
            name="Palika",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                ("location_id", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_deliverable",
                    models.BooleanField(default=False, verbose_name="Is Deliverable"),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="location.district",
                        verbose_name="District",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "unique_together": {("name", "district")},
            },
        ),
        migrations.AddField(
            model_name="district",
            name="province",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="location.province",
                verbose_name="Province",
            ),
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(verbose_name="Number")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wards",
                        to="location.palika",
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ward",
                "verbose_name_plural": "Wards",
                "unique_together": {("number", "location")},
            },
        ),
    ]
