# Generated by Django 5.2.4 on 2025-07-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="nepali_name",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AddField(
            model_name="palika",
            name="nepali_name",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
        migrations.AddField(
            model_name="province",
            name="nepali_name",
            field=models.CharField(blank=True, default="", max_length=70),
        ),
    ]
