# Generated by Django 5.2.4 on 2025-11-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="full name max length=152",
                        max_length=152,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Customer phone number", max_length=20, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Customer address")),
                (
                    "loyalty_points",
                    models.PositiveIntegerField(
                        default=0, help_text="Loyalty points earned"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is the customer active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
