# Generated by Django 5.2.4 on 2025-11-25 09:32

import apps.authentication.models.users
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("location", "0002_district_nepali_name_palika_nepali_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person contacting us.", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the person contacting us.",
                        max_length=255,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject of the contact message.", max_length=255
                    ),
                ),
                ("message", models.TextField(help_text="Message from the user.")),
            ],
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": "Contact Us",
            },
        ),
        migrations.CreateModel(
            name="PermissionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name can have max of 50 characters", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Category",
                "verbose_name_plural": "Permission Categories",
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(help_text="User code.", max_length=50)),
                (
                    "email",
                    models.EmailField(help_text="Email address .", max_length=255),
                ),
                (
                    "otp",
                    models.CharField(
                        help_text="One-time password for verification.",
                        max_length=6,
                        unique=True,
                    ),
                ),
            ],
            options={
                "unique_together": {("email", "code")},
            },
        ),
        migrations.CreateModel(
            name="CustomPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name can have max of 50 characters", max_length=50
                    ),
                ),
                (
                    "code_name",
                    models.CharField(
                        help_text="Code Name can have max of 50 characters",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="null=True, blank=True",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.permissioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name can have max of 50 characters", max_length=50
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="by default=True"),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="blank=True",
                        related_name="roles",
                        to="authentication.custompermission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address. Max Length: 255 characters",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Username must be unique and max_length upto 50 characters",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name can have max_length upto 50 characters, blank=True",
                        max_length=50,
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Middle name can have max_length upto 50 characters, blank=True",
                        max_length=50,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name can have max_length upto 50 characters, blank=True",
                        max_length=50,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="full name max length=152",
                        max_length=152,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "MALE"),
                            ("female", "FEMALE"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        help_text="Choices are male, female, and other. Default=male",
                        max_length=30,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("waiter", "WAITER"),
                            ("cleaner", "CLEANER"),
                            ("manager", "MANAGER"),
                            ("cook", "COOK"),
                            ("system", "SYSTEM"),
                        ],
                        help_text="Choices are school, student, public, system",
                        max_length=30,
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Blank=True and null=True", null=True
                    ),
                ),
                (
                    "palika",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Municipality name",
                        max_length=100,
                    ),
                ),
                ("ward_no", models.PositiveIntegerField(default=1)),
                ("tole", models.CharField(blank=True, default="", max_length=100)),
                (
                    "mobile_no",
                    models.CharField(
                        blank=True,
                        help_text="Mobile no. should be maximum of 15 characters",
                        max_length=15,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="default_images/profile.png",
                        upload_to=apps.authentication.models.users.upload_path_user,
                        validators=[apps.authentication.models.users.validate_image],
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="location.district",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="authentication.custompermission"
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(blank=True, to="authentication.roles"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("created_by", models.IntegerField(default=0, editable=False)),
                ("modified_by", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "created_at_bs",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "MOBILE"),
                            ("pc", "PC"),
                            ("tablet", "TABLET"),
                            ("other", "OTHER"),
                        ],
                        default="mobile",
                        editable=False,
                        help_text="Enum field for the device type.",
                        max_length=10,
                    ),
                ),
                (
                    "os_type",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("ios", "IOS"),
                            ("android", "ANDROID"),
                            ("mac", "MAC"),
                            ("linux", "LINUX"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        editable=False,
                        help_text="Enum field for the app type.",
                        max_length=10,
                    ),
                ),
                ("bio", models.TextField(blank=True, help_text="User biography.")),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Link to the user this profile belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
