"""
Django settings for restaurant_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from decouple import config

from .db import DATABASE as DATABASES_
from .rest import REST_FRAMEWORK_CONFIGS
from .settings_config import CONFIG_DEBUG, CONFIG_SECRET_KEY
from .simple_jwt import SIMPLE_JWT_CONFIGS
from .spectacular import SPECTACULAR_SETTINGS_

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-7ere@p2d1&^31m!g#3hcypg1+=mfgizny=m59tmr9i&q0h=e--"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

DEBUG = CONFIG_DEBUG

ALLOWED_HOSTS = ["*"]


DEBUG = CONFIG_DEBUG
SECRET_KEY = CONFIG_SECRET_KEY

# Application definition
DISABLED_AUTHENTICATION = config("DISABLED_AUTHENTICATION", cast=bool, default=False)

THIRD_PARTY_APPS = [
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "django_filters",
    "rest_framework_simplejwt.token_blacklist",
    "django_user_agents",
]

LOCAL_APPS = [
    "apps.authentication",
    "apps.customer",
    "apps.location",
    "apps.api_logs",
    "apps.core",
]
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

INSTALLED_APPS += LOCAL_APPS
INSTALLED_APPS += THIRD_PARTY_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_user_agents.middleware.UserAgentMiddleware",
    "apps.api_logs.middleware.ApiLog",
]

ROOT_URLCONF = "restaurant_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
ASGI_ENV = config("ASGI_ENV", cast=bool, default=True)

if ASGI_ENV:
    ASGI_APPLICATION = "restaurant_backend.asgi.application"
else:
    WSGI_APPLICATION = "restaurant_backend.wsgi.application"

DECIMAL_PLACES = config("DECIMAL_PLACES", cast=int, default=4)
MAX_DIGITS = config("MAX_DIGITS", cast=int, default=12)
MAX_DECIMAL_DIGITS = config("MAX_DECIMAL_DIGITS", cast=int, default=16)

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
DATABASES = DATABASES_


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
if not os.path.exists(STATIC_ROOT):
    os.mkdir(STATIC_ROOT)

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "authentication.CustomUser"

APPEND_SLASH = False

SPECTACULAR_SETTINGS = SPECTACULAR_SETTINGS_

CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="http://127.0.0.1").split(
    ","
)
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS_", cast=bool, default="False")

SIMPLE_JWT = SIMPLE_JWT_CONFIGS
REST_FRAMEWORK = REST_FRAMEWORK_CONFIGS

# env data for global settings
MAX_UPLOAD_SIZE = config("MAX_UPLOAD_SIZE", cast=int, default=2097152)


SECURE_PROXY = config("SECURE_PROXY", cast=bool, default=False)
if SECURE_PROXY:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_PASSWORD = config("EMAIL_PASS", default="")
EMAIL_HOST_USER = config("EMAIL_USER", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="")

DATA_UPLOAD_MAX_MEMORY_SIZE = 25242880
